apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: oficina
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: techchallenge-oficina
type: Opaque
stringData:
  POSTGRES_PASSWORD: "P@ssw0rd123"
